name: Gitea CI/CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest:docker://node:18-bullseye,ubuntu-22.04:docker://node:18-bullseye
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, Gitea Actions! กำลังทดสอบระบบ CI/CD"

      - name: Run a multi-line script
        run: |
          echo "ลองเช็คเวอร์ชันของเครื่องรัน:"
          node -v
